### ISSUE TITLE
Morse fails to initialse when running on Manjaro

### ISSUE THREAD

**Issue by rodneyrod** [TelepathyQt/telepathy-morse#11]
I'm testing Netrunner Rolling, and after installing Morse from the AUR, the program displays the confirmation code fine and accepts it, but it only ended up downloading a single friend and then hung at the _connecting_ dialog.
I'm not too sure how to extract logs or run it in debug mode, but as soon as I do I'll post a gist with the logs here.

**Comment by Kaffeine** [comment]
Sure, I need the application output to suppose, what happened.
One of possible ways to get the output is to manually run the connection manager from terminal, before it'll be started automatically by Telepathy stack.
