### ISSUE TITLE
defaultPingInterval() is no longer part of CTelegramCore

### ISSUE THREAD

**Issue by Steinhagen** [TelepathyQt/telepathy-morse#17]
The commit 8e701b53fd9d54df8388dd22127f736e7b5a7a43 should either be temporary reverted, or an alternative solution must be found to reimplement keep alive interval.

**Comment by Kaffeine** [comment]
Why do you think that the method is not a part of CTelegramCore? https://github.com/Kaffeine/telegram-qt/blob/master/telegram-qt/CTelegramCore.hpp#L42
I'm going to close this as invalid issue.
