### ISSUE TITLE
Implement telepathy debug interface

### ISSUE THREAD

**Issue by ItachiSan** [TelepathyQt/telepathy-morse#19]
It would be nice to declare the debugging interface for empathy-debugger.
I noticed that, if I run manually telepathy-morse, it prints out some debug messages. Why they are not catched by empathy-debugger?

**Comment by Kaffeine** [comment]
Hi.

https://telepathy.freedesktop.org/spec/Debug.html

We still have to implement the debug interface support  in TelepathyQt and after that in morse.
I'm planning to do it sometime soon, I think it would be done in the next two weeks.
(You'll have to use both telepathy-qt and telepathy-morse from git)

**Comment by ItachiSan** [comment]
Perfect, waiting for it! :)

**Comment by Kaffeine** [comment]
I implemented the interface in telepathy-qt@6d9cfcea82c921d4d973a643b6b571f54e5605cf, but it's not a trivial thing to nicely route all debug output in the CM.

Right now I have a dirty output, such as (I'm using ktp-debugger):
02.03.2016 22:55:49.43999 - [/home/kaffeine/projects/telepathy/bundle/telepathy-qt/examples/morse/telegram-qt/CTelegramDispatcher.cpp:1119 CTelegramDispatcher::whenUsersReceived(const QVector<TLUser>&) 2

It makes sense to put filename, line or a function name into "domain", but it's often duplicated in the debug message.

I'll try to sort this and push something soon.

**Comment by Kaffeine** [comment]
Done via f2b999e Enabled for TelepathyQt-0.9.7 by f5353de.
