### ISSUE TITLE
Messages that are sent while offline are not received

### ISSUE THREAD

**Issue by TemeV** [TelepathyQt/telepathy-morse#2]
If someone sends a message while the device is offline this message is not received. This feature used to work before. I'm not sure if this is an issue in telepathy-morse or telegram-qt though.

Steps to reproduce:
1. Go offline.
2. Send your self a message from another account.
3. Go online. The message is not received.

**Comment by Kaffeine** [comment]
Thank you! I think I've checked it. I'll look and fix it next 12 hours. :-)

**Comment by Kaffeine** [comment]
Things used to takes more time, than expected. :/
Just got time to fix it. Closed in 21c7dbf0d301c22b6cc81596bd625c8a10062bbe. :)
