### ISSUE TITLE
Could not make

### ISSUE THREAD

**Issue by wiacz** [TelepathyQt/telepathy-morse#24]
I can't make it after using cmake:

make -j4
Scanning dependencies of target telepathy-morse_automoc
[ 14%] Automatic moc for target telepathy-morse
Generating moc_connection.cpp
Generating moc_protocol.cpp
Generating moc_textchannel.cpp
[ 14%] Built target telepathy-morse_automoc
Scanning dependencies of target telepathy-morse
[ 28%] Building CXX object CMakeFiles/telepathy-morse.dir/main.cpp.o
[ 42%] Building CXX object CMakeFiles/telepathy-morse.dir/connection.cpp.o
[ 71%] Building CXX object CMakeFiles/telepathy-morse.dir/textchannel.cpp.o
[ 71%] Building CXX object CMakeFiles/telepathy-morse.dir/protocol.cpp.o
[ 85%] Building CXX object CMakeFiles/telepathy-morse.dir/telepathy-morse_automoc.cpp.o
[100%] Linking CXX executable telepathy-morse
/usr/bin/ld: cannot open output file telepathy-morse: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/telepathy-morse.dir/build.make:208: recipe for target 'telepathy-morse' failed
make[2]: **\* [telepathy-morse] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/telepathy-morse.dir/all' failed
make[1]: **\* [CMakeFiles/telepathy-morse.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Kaffeine** [comment]
Hi.

Where are you ran cmake? It looks like you're building in the telepathy-morse source parent directory.

```
/usr/bin/ld: cannot open output file telepathy-morse: Is a directory
```

For sure, it is not possible for linker to create telepathy-morse binary if there is a directory with the same name.

Use an empty directory for build.

**Comment by wiacz** [comment]
Amm, I am sorry))
