### ISSUE TITLE
Automatic reconnecting is not always working

### ISSUE THREAD

**Issue by TemeV** [TelepathyQt/telepathy-morse#3]
Automatic connection is not working reliably. Here is piece of log where Morse stayed offline. At least this time there had been a reconnect a minute earlier (bad reception), not sure if it is related. 

[D] MorseConnection::setSubscriptionState:637 - void MorseConnection::setSubscriptionState(const QStringList&, const QList<unsigned int>&, uint) 
[D] CTelegramDispatcher::whenConnectionStatusChanged:1727 - void CTelegramDispatcher::whenConnectionStatusChanged(int, quint32) status 0 dc 2 
[D] CTelegramDispatcher::setConnectionState:1149 - void CTelegramDispatcher::setConnectionState(TelegramNamespace::ConnectionState) 0 
[D] MorseConnection::whenConnectionStateChanged:190 - void MorseConnection::whenConnectionStateChanged(TelegramNamespace::ConnectionState) 0 
[D] Tp::Debug::invokeDebugCallback:146 - tp-qt 0.9.4 DEBUG: BaseConnection::status =  0   MorseConnection(0x181b478)  
[D] Tp::Debug::invokeDebugCallback:146 - tp-qt 0.9.4 DEBUG: BaseConnection::setStatus  2   2   MorseConnection(0x181b478)  
[D] MorseConnection::whenDisconnected:765 - void MorseConnection::whenDisconnected() 
[D] Tp::Debug::invokeDebugCallback:146 - tp-qt 0.9.4 DEBUG: BaseConnection::setStatus  2   1   MorseConnection(0x181b478)  
[W] QAbstractSocket::waitForBytesWritten:2150 - QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState

**Comment by Kaffeine** [comment]
Expected to be fixed in kaffeine/telegram-qt@3148a69d223225e0173d09c470ad0e6e0ba64d93 and kaffeine/telepathy-morse@572cd8f9709aedadacadd1350737a396203728ba.

**Comment by TemeV** [comment]
I left this version running for a night, and by morning it was disconnected. I think the problem is "[D] Tp::Debug::invokeDebugCallback:146 - tp-qt 0.9.4 DEBUG: BaseConnection::setStatus 2 1". There the reason is set to "ConnectionStatusReasonRequested" and after that Mission Control doesn't reconnect. 

I'm now testing a version where "setStatus(Tp::ConnectionStatusDisconnected, Tp::ConnectionStatusReasonRequested);" in MorseConnection::whenDisconnected() is not called after a disconnect caused by network error.

**Comment by TemeV** [comment]
It seems my problem is, that the 15 second ping time out in telegram-qt is too short. I think when my phone goes to sleep mode, morse doesn't get the CPU time required to send the pings in time. This causes Morse to disconnect very often and I guess that the Mission Control gives up on reconnecting eventually. I could actually get disconnected in a couple of minutes most of the time. I try to increase the timeout and see if it helps.

**Comment by TemeV** [comment]
Now almost 3 days and no disconnect without reconnecting so I'd say longer timeout period solves the problem.
