### ISSUE TITLE
License in files

### ISSUE THREAD

**Issue by ecsgh** [TelepathyQt/telepathy-morse#33]
Hello,

i made packages for opensuse but my request was declined because of  not properly licensed files.
Can you please correct this?

**Comment by Kaffeine** [comment]
Hello.

I realised too late that my "As is" in the sources can cause such problems. Yesterday I made this commit 8bbf7a8f708913427975ffde085121ff7d564260 "Clarified license."

What exactly I can do now?

**Comment by ecsgh** [comment]
Am Mi 21 Sep 2016, 10:03:52 schrieb Alexandr Akulich:

> Hello.
> 
> I realised that my "As is" in the sources can cause such problems. Yesterday
> I made this commit 8bbf7a8f708913427975ffde085121ff7d564260 "Clarified
> license."
> 
> What exactly I can do now?

Ah. Okay. I don't see it, because the release was still 0.1.0

I think and hope this is okay. I will try it.

Must i use a patch or can you make a new release (0.1.1?) or rebase the 
actualy 0.1.0 release.?

Regards
 Eric

**Comment by ecsgh** [comment]
Am Mi 21 Sep 2016, 10:03:52 schrieb Alexandr Akulich:
> Hello.
> 
> I realised that my "As is" in the sources can cause such problems. Yesterday
> I made this commit 8bbf7a8f708913427975ffde085121ff7d564260 "Clarified
> license."
> 
> What exactly I can do now?

Ah. Okay. I don't see it, because the release was still 0.1.0

I think and hope this is okay. I will try it.

Must i use a patch or can you make a new release (0.1.1?) or rebase the 
actualy 0.1.0 release.?

Regards
 Eric

**Comment by ecsgh** [comment]
Am Mi 21 Sep 2016, 10:03:52 schrieb Alexandr Akulich:
> Hello.
> 
> I realised that my "As is" in the sources can cause such problems. Yesterday
> I made this commit 8bbf7a8f708913427975ffde085121ff7d564260 "Clarified
> license."
> 
> What exactly I can do now?

Ah. I don't see it, because releae is still 0.1.0

I think and hope it is ok now.
I will try it.

Must i patch the package or can you generate a new release or rebase the 0.1.0 
release?


Regards
 Eric

**Comment by Kaffeine** [comment]
I think you can just apply the patch. If it will not work for you, then may be I can release 0.1.1, though I would like to have some actual fixes for this one.

**Comment by ecsgh** [comment]
okay. It was accepted.
This 'bug' is fixed.
Thank you

**Comment by Kaffeine** [comment]
That's good. Thank you!
