### ISSUE TITLE
https://quickgit.kde.org/?p=telepathy-morse.git?

### ISSUE THREAD

**Issue by davewthompson** [TelepathyQt/telepathy-morse#36]
Hi there,

What's the relationship between this project and https://quickgit.kde.org/?p=telepathy-morse.git? Are they just competing implementations?

Thanks,

Dave

**Comment by Kaffeine** [comment]
Hello.

This and the mentioned repositories belongs to the same project.
I had to host the project on kde.org first, but then got reasons to move the repository (repositories) here.
