### ISSUE TITLE
Can't build the plugin : No telepathy-morse.pro file in the sources

### ISSUE THREAD

**Issue by mathojojo** [TelepathyQt/telepathy-morse#37]
Hello,

I tried to build telepathy-morse, using readme file.
The command : cmake ../telepathy-morse does'nt work, as the file telepathy-morse is missing.

So there are two cases : 
case 1 : The file is really missing, and it should be added.
case 2 : The procedure changed, and this file is no more needed. So the readme should be modified.

Thank you

**Comment by Kaffeine** [comment]
Thank you for the report.
We have the second or the third case: I forgot to add `-0.1.0` to the readme file before the release. There is also a yet another issue: I didn't expect that github will concatenate the project name and the tag to build the archive directory name.
You could notice that the archive contains "telepathy-morse-telepathy-morse-0.1.0" directory and it is what you're expected to pass to cmake.
`cmake ../telepathy-morse-telepathy-morse-0.1.0`

I will try to work this out to have both archive and directory named telepathy-morse-0.1.0 and also I will update the readme.

**Comment by Kaffeine** [comment]
There is .pro file since 6756b18726e105603343ad1c9425fc58f190ee7d.

Also, I will double check content of the archive and will update the instruction for 0.2.0 release.
