### ISSUE TITLE
Sides Switched

### ISSUE THREAD

**Issue by criztovyl** [TelepathyQt/telepathy-morse#46]
Hello,

recently telepathy-morse started switching the sides who sent the message, i.e. if someone sends *me* a message it appears as *sent by me* and if I send a message it displays as sent by the other party.

 - Empathy
 - telepathy-morse@3df9f86 (master)
 - telegram-qt@056a3fe (master)

I will try to capture some logs.

**Comment by Kaffeine** [comment]
Works for me with KDE Telepathy and Jolla-Messages (Sailfish OS).

**Comment by Kaffeine** [comment]
Also works with Empathy-3.12.12.
