### ISSUE TITLE
README missing

### ISSUE THREAD

**Issue by peperunas** [TelepathyQt/telepathy-morse#8]
Hello, is it possible to have a complete README file including installation, changelog, whatsoever? Thank you very much.

**Comment by Kaffeine** [comment]
Hi. I'll do it soon, this week probably.

**Comment by juhi24** [comment]
I would also appreciate a README, thanks.

**Comment by Kaffeine** [comment]
You're 100% right. I need to do it.

**Comment by Kaffeine** [comment]
I just added README.md.
Let me know, if you need any extra information.

I need to add similar readme to TelegramQt. I'll try to do it tomorrow.
In short: TelegramQt have the same CMake options.

**Comment by TemeV** [comment]
"Authentication doesn't work on the Sailfish OS (show-stopper)."
I wouldn't list that as a show stopper, and maybe not even as a morse issue, since it is an Sailfish issue, not Morse. I don't think there is anything that can be done on Morse side to make it work (besides some dirty hack).

**Comment by Kaffeine** [comment]
I got an idea of some bad and dirty workaround: we can configure TelegramQt testApp to save auth info into the same location as Morse. This way Sailfish user would be able to start session with testApp and continue with telepathy.

**Comment by TemeV** [comment]
I had a same kind of idea, making a "Morse registration" app that people can use for registering. It shouldn't be too hard to do, basically just stealing the essential code from testApp or Morse and creating a nice UI with QML.

**Comment by Kaffeine** [comment]
:+1:
